image: node:10

stages:
  - build
  - test
  - deploy staging # This is CD pipeline in environment test (o stage test)
  - deploy production # This is CD pipeline in environment prod (o stage prod)
  - production tests # This is CD pipeline in environment prod (o stage prod)

# Cache for optimize build speed
cache:
  key: ${CI_COMMIT_REF_SLUG} # Environment variable with url of branch or tag
  paths:
    - node_modules/

# Add variables
variables:
  STAGING_DOMAIN: terrible-paper-staging.surge.sh
  PRODUCTION_DOMAIN: terrible-paper.surge.sh

# Environment variable with commit SHA
build website:
  stage: build
  only:
    - master # Only branch master it do this job
    - merge_requests # Only branch merge_request it do this job
  script:
    - echo $CI_COMMIT_SHORT_SHA
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
    - sed -i "s/%%VERSION%%/$CI_COMMIT_SHORT_SHA/" ./public/index.html # Environment variable with commit SHA
  artifacts:
    paths:
      - ./public

# This jobs are execute in parallel
test artifact:
  image: alpine
  stage: test
  only:
    - master # Only branch master it do this job
    - merge_requests # Only branch merge_request it do this job
  script:
    - grep -q "Gatsby" ./public/index.html

test website:
  stage: test
  only:
    - master # Only branch master it do this job
    - merge_requests # Only branch merge_request it do this job
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby serve &
    - sleep 3
    - curl "http://localhost:9000" | tac | tac | grep -q "Gatsby" # Optimize jobs

# This is CD pipeline
deploy staging:
  stage: deploy staging
  environment:
    name: staging
    url: http://$STAGING_DOMAIN
  only:
    - master # Only branch master it do this job
  script:
    - npm install --global surge
    - surge --project ./public --domain $STAGING_DOMAIN

deploy production:
  stage: deploy production
  environment:
    name: production
    url: $PRODUCTION_DOMAIN
  only:
    - master # Only branch master it do this job
  script:
    - npm install --global surge
    - surge --project ./public --domain $PRODUCTION_DOMAIN

production tests:
  image: alpine
  stage: production tests
  only:
    - master # Only branch master it do this job
  script:
    - apk add --no-cache curl
    - curl -s "https://$PRODUCTION_DOMAIN" | grep -q "Hi people"
    - curl -s "https://$PRODUCTION_DOMAIN" | grep -q "$CI_COMMIT_SHORT_SHA"
