image: node:10

stages:
  - build
  - test
  - deploy # This is CD pipeline
  - deployment tests # This is CD pipeline

# Cache for optimize build speed
cache:
  key: ${CI_COMMIT_REF_SLUG} # Environment variable with url of branch or tag
  paths:
    - node_modules/

build website:
  stage: build
  script:
    - echo $CI_COMMIT_SHORT_SHA
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
    - sed -i "s/%%VERSION%%/$CI_COMMIT_SHORT_SHA/" ./public/index.html # Environment variable with commit SHA
  artifacts:
    paths:
      - ./public

# This jobs are execute in parallel
test artifact:
  image: alpine
  stage: test
  script:
    - grep -q "Gatsby" ./public/index.html

test website:
  stage: test
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby serve &
    - sleep 3
    - curl "http://localhost:9000" | tac | tac | grep -q "Gatsby" # Optimize jobs

# This is CD pipeline
deploy to surge:
  stage: deploy
  script:
    - npm install --global surge
    - surge --project ./public --domain terrible-paper.surge.sh

test deployment:
  image: alpine
  stage: deployment tests
  script:
    - apk add --no-cache curl
    - curl -s "https://terrible-paper.surge.sh" | grep -q "Welcome to Gatsby!"
    - curl -s "https://terrible-paper.surge.sh" | grep -q "$CI_COMMIT_SHORT_SHA"
