image: node:10

stages:
  - build
  - test
  - deploy review # This is CD pipeline in temporal environment
  - deploy staging # This is CD pipeline in environment test (o stage test)
  - deploy production # This is CD pipeline in environment prod (o stage prod)
  - production tests # This is CD pipeline in environment prod (o stage prod)

# Cache for optimize build speed
cache:
  key: ${CI_COMMIT_REF_SLUG} # Environment variable with url of branch or tag
  paths:
    - node_modules/

# Add variables
variables:
  STAGING_DOMAIN: terrible-paper-staging.surge.sh
  PRODUCTION_DOMAIN: terrible-paper.surge.sh

# Environment variable with commit SHA
build website:
  stage: build
  only:
    - master # Only branch master it do this job
    - merge_requests # Only branch merge_request it do this job
  script:
    - echo $CI_COMMIT_SHORT_SHA
    - npm install
    - npm install -g gatsby-cli
    - gatsby build
    - sed -i "s/%%VERSION%%/$CI_COMMIT_SHORT_SHA/" ./public/index.html # Environment variable with commit SHA
  artifacts:
    paths:
      - ./public

test artifact:
  image: alpine
  stage: test
  only:
    - master # Only branch master it do this job
    - merge_requests # Only branch merge_request it do this job
  script:
    - grep -q "Gatsby" ./public/index.html

test website:
  stage: test
  only:
    - master # Only branch master it do this job
    - merge_requests # Only branch merge_request it do this job
  script:
    - npm install
    - npm install -g gatsby-cli
    - gatsby serve &
    - sleep 3
    - curl "http://localhost:9000" | tac | tac | grep -q "Gatsby" # Optimize jobs

# This is CD pipeline
deploy review:
  stage: deploy review
  only:
    - merge_requests # Only branch merge_request it do this job
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://terrible-paper-$CI_ENVIRONMENT_SLUG.surge.sh
    on_stop: stop review
  script:
    - npm install --global surge
    - surge --project ./public --domain terrible-paper-$CI_ENVIRONMENT_SLUG.surge.sh

stop review:
  stage: deploy review
  only:
    - merge_requests # Only branch merge_request it do this job
  variables:
    GIT_STRATEGY: none
  script:
    - npm install --global surge
    - surge teardown terrible-paper-$CI_ENVIRONMENT_SLUG.surge.sh
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop

# . is for disable job
.deploy_template: &deploy # Declarate anchor
  only:
    - master # Only branch master it do this job
  script:
    - npm install --global surge
    - surge --project ./public --domain $DOMAIN
  environment:
    url: http://$DOMAIN

deploy staging:
  <<: *deploy # Invoke
  stage: deploy staging
  variables:
    DOMAIN: $STAGING_DOMAIN
  environment:
    name: staging

deploy production:
  <<: *deploy # Invoke
  stage: deploy production
  variables:
    DOMAIN: $PRODUCTION_DOMAIN
  environment:
    name: production

production tests:
  image: alpine
  stage: production tests
  only:
    - master # Only branch master it do this job
  script:
    - apk add --no-cache curl
    - curl -s "https://$PRODUCTION_DOMAIN" | grep -q "Hi people"
    - curl -s "https://$PRODUCTION_DOMAIN" | grep -q "$CI_COMMIT_SHORT_SHA"
